config/routes.rb
Rails.application.routes.draw do

  get '/:locale' => 'home#index'

  scope "(:locale)", :locale => /en|fr/ do
    root 'home#index'

    get 'home/index'
    get 'sponsor/index'
    get 'entry/index'

    get 'entry/vote/:id', :to => 'entry#vote#', :as => 'entry_vote'
    post 'entry/send_vote', :as => 'entry_votes'
    get 'entry/send_vote'
    get 'entry/confirm_vote/:id', :to => 'entry#confirm_vote', :as => 'entry_confirm_vote'

    get 'entry/submit', :to => 'entry#submit'
    post 'entry/send_submit', :as => 'skate_entries'
    get 'entry/send_submit'
    get 'entry/confirm_submit/:id', :to => 'entry#confirm_submit', :as => 'entry_confirm_submit'

    get 'entry/pending'
    get 'entry/validate/:id/:value', :to => 'entry#validate'

    get 'sponsor/join', :to => 'sponsor#join'
    post 'sponsor/send_join', :as => 'sponsors'
    get 'sponsor/send_join'
    get 'sponsor/confirm_join/:id', :to => 'sponsor#confirm_join', :as => 'sponsor_confirm_join'

    get 'sponsor/pending'
    get 'sponsor/validate/:id/:value', :to => 'sponsor#validate'

    get 'home/set_lang/:id', :to => 'home#set_lang'

  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry_seasoning.rb
class EntrySeasoning < ApplicationRecord
  has_many :skate_entries, :dependent => :destroy, :foreign_key => :entry_seasonings_id
end

app/models/entry_vote.rb
class EntryVote < ApplicationRecord
  belongs_to :skate_entry, :foreign_key => :skate_entries_id
  accepts_nested_attributes_for :skate_entry

  validates :mail, :presence => true, :uniqueness => true

  before_create :confirmation_token

  def vote_confirmed
    self.confirmed = true
    self.token = nil
    self.skate_entry.increment_rate

    self.save!(:validate => false)
  end

  private
  def confirmation_token
    if self.token.blank?
      self.token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

app/models/skate_entry.rb
class SkateEntry < ApplicationRecord
  belongs_to :entry_seasoning, :foreign_key => :entry_seasonings_id
  has_many :entry_votes, :dependent => :destroy, :foreign_key => :skate_entries_id
  accepts_nested_attributes_for :entry_seasoning

  validates :mail, :presence => true, :uniqueness => { :scope => :entry_seasoning }

  before_create :confirmation_token

  def submit_confirmed
    self.submitted = true
    self.token = SecureRandom.urlsafe_base64.to_s

    self.save!(:validate => false)
  end

  def increment_rate
    self.rate += 1

    self.save!(:validate => false)
  end

  def validate(value)
    self.validated = value
    self.token = nil
    self.save!(:validate => false)
  end

  private
  def confirmation_token
    if self.token.blank?
      self.token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  validates :name, :presence => true
  validates :mail, :presence => true, :uniqueness => true
  validates :website, :presence => true
  validates :image, :presence => true

  before_create :confirmation_token

  def sponsor_confirmed
    self.submitted = true
    self.token = SecureRandom.urlsafe_base64.to_s

    self.save!(:validate => false)
  end

  def validate(value)
    self.validated = value
    self.token = nil
    self.save!(:validate => false)
  end

  private
  def confirmation_token
    if self.token.blank?
      self.token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def sponsor_params
    params.require(:sponsor).permit(:name, :mail, :website, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_local
  protect_from_forgery with: :exception

  def set_local
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
    currentSeasoning = EntrySeasoning.find(1)
    seasoning = EntrySeasoning.where('id > 1',season: currentSeasoning.season, week: currentSeasoning.week).first
    @entries = SkateEntry.where(entry_seasonings_id: seasoning.id, validated: true).order(rate: :desc, created_at: :desc)
  end

  def vote
    entry = SkateEntry.find(params.required(:id))
    @vote = entry.entry_votes.build
  end

  def send_vote
    entry = SkateEntry.find(params[:entry_vote][:skate_entry_attributes][:id])
    params[:entry_vote].delete(:skate_entry_attributes)
    @vote = entry.entry_votes.create(vote_params)
    if @vote.save
      ApplicationMailer.vote_confirmation(@vote).deliver
    else
      render 'vote'
    end
  end

  def confirm_vote
    @vote = EntryVote.find_by_token(params[:id])
    if @vote && (@vote.created_at - DateTime.now).hour < 24
      @vote.vote_confirmed
    end
  end

  def submit
    seasoning = EntrySeasoning.find(2)
    @entry = seasoning.skate_entries.build
  end

  def send_submit
    seasoning = EntrySeasoning.find(params[:skate_entry][:entry_seasoning_attributes][:id])
    params[:skate_entry].delete(:entry_seasoning_attributes)
    @entry = seasoning.skate_entries.create(skate_entry_params)
    if @entry.save
      ApplicationMailer.entry_confirmation(@entry).deliver
    else
      render 'submit'
    end
  end

  def confirm_submit
    @entry = SkateEntry.find_by_token(params[:id])
    if @entry && (@entry.created_at - DateTime.now).hour < 24
      @entry.submit_confirmed
    end
  end

  def pending
    @entries = SkateEntry.where(:validated => false)
  end

  def validate
    entry = SkateEntry.find_by_token(params[:id])
    if entry
      entry.validate(params[:value])
    end
    if !entry.validated
      entry.destroy
    end
    redirect_to entry_pending_path
  end

  private
  def skate_entry_params
    params.required(:skate_entry).permit(:skater, :link, :mail)
  end

  def vote_params
    params.required(:entry_vote).permit(:mail)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    currentSeasoning = EntrySeasoning.find(1)
    seasoning = EntrySeasoning.where('id > 1',season: currentSeasoning.season, week: currentSeasoning.week).first
    @entries = SkateEntry.where(entry_seasonings_id: seasoning.id, validated: true).order(rate: :desc, created_at: :desc).limit(4)
    @sponsors = Sponsor.where(validated: true).all.limit(4)
  end
end

app/controllers/sponsor_controller.rb
class SponsorController < ApplicationController
  def index
    @sponsors = Sponsor.where(validated: true).all
  end

  def join
    @sponsor = Sponsor.new
  end

  def send_join
    @sponsor = Sponsor.create(sponsor_params)
    if (@sponsor.save)
      ApplicationMailer.sponsor_confirmation(@sponsor).deliver
    else
      render 'join'
    end
  end

  def confirm_join
    @sponsor = Sponsor.find_by_token(params[:id])
    if @sponsor && (@sponsor.created_at - DateTime.now).hour < 24
      @sponsor.sponsor_confirmed
    end
  end

  def pending
    @sponsors = Sponsor.where(:validated => false)
  end

  def validate
    sponsor = Sponsor.find_by_token(params[:id])
    if sponsor
      sponsor.validate(params[:value])
    end
    if !sponsor.validated
      sponsor.destroy
    end
    redirect_to sponsor_pending_path
  end

  private
  def sponsor_params
    params.require(:sponsor).permit(:name, :mail, :website, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def last_entry
    @jumbo = SkateEntry.order(rate: :desc).first
  end
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def currentSeasoning
    return EntrySeasoning.find(1)
  end

  def getSeasons
    return EntrySeasoning.where('id > 1').select(:season).distinct.order(season: :desc)
  end

  def getWeekBySeason(season)
    return EntrySeasoning.where('id > 1', season: season).select(:week).distinct.order(week: :desc)
  end
end

app/helpers/sponsor_helper.rb
module SponsorHelper
end

app/views/entry/confirm_submit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <% if @entry %>
          <div class="card-header card-primary">
            <h1><%= t('.header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.content_html', :name => @entry.skater) %>
          </div>
      <% else %>
          <div class="card-header card-danger">
            <h1><%= t('.error_header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.error_content_html') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entry/confirm_vote.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <% if @vote %>
          <div class="card-header card-primary">
            <h1><%= t('.header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.content_html', :name => @vote.skate_entry.skater) %>
          </div>
      <% else %>
          <div class="card-header card-primary">
            <h1><%= t('.error_header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.error_content_html') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entry/index.html.erb
<!--
<% getSeasons.each do |seasons| %>
      <ul>Season <%= seasons.season %>
    <% getWeekBySeason(seasons).each do |week| %>
          <li>Week <%= week.week %></li>
      <% end %>
      </ul>
    <% end %>
-->

<div class="row">
  <div class="col-md-12">
    <% currentSeason = currentSeasoning %>
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-10">
            <h2><%= t(:season) %> <%= currentSeason.season %> <%= t(:week) %> <%= currentSeason.week %></h2>
          </div>
          <div class="col-md-2">
            <%= link_to(t(:submit), entry_submit_path, :class => "btn btn-success btn-block")  %>
          </div>
        </div>
      </div>
      <div class="card-block">
        <div class="row">
          <% @entries.each do |entry| %>
              <div class="col-md-6 mb-4">
                <div class="card" id="<%= entry.id %>">
                  <div class="card-header">
                    <div class="row">
                      <div class="col-md-6 offset-md-6">
                        <div class="row">
                          <div class="col-md-7">
                            <div class="row">
                              <span class="col-md-7"><%= t(:votes_label) %></span><span class="font-weight-bold h4 text-right col-md-5"><%= entry.rate %></span>
                            </div>
                          </div>
                          <div class="col-md-5">
                            <%= link_to entry_vote_path(:id => entry.id), :class => "btn btn-primary btn-block" do  %>
                                <i class="fa fa-thumbs-o-up"></i>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-img-top">
                    <div class="embed-responsive embed-responsive-16by9 col-md-12 text-center media-object">
                      <iframe class="embed-responsive-item img-rounded" src="https://www.youtube.com/embed/<%= entry.link %>?autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>
                    </div>
                  </div>
                  <div class="card-footer">
                    <h4 class="card-title"><%= entry.skater %></h4>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entry/pending.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-md-10">
          <h2><%= t(:entry_label) %></h2>
        </div>
      </div>
    </div>
    <div class="card-block">
      <div class="card-deck-wrapper">
        <div class="card-deck">
          <% @entries.each do |entry| %>
              <div class="card" id="<%= entry.id %>">
                <div class="card-header">
                  <div class="row">
                    <div class="col-md-12">
                      <h4 class="card-title"><%= entry.skater %></h4>
                    </div>
                  </div>
                </div>
                <div class="card-img-top">
                  <div class="embed-responsive embed-responsive-16by9 col-md-12 text-center media-object">
                    <iframe class="embed-responsive-item img-rounded" src="https://www.youtube.com/embed/<%= entry.link %>?autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/entry/send_submit.html.erb
<% if @entry %>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h2><%= t('.header') %></h2>
          </div>
          <div class="card-block">
            <%= t('.content_html') %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/entry/send_vote.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <% if @vote %>
          <div class="card-header card-primary">
            <h2><%= t('.header') %></h2>
          </div>
          <div class="card-block">
            <%= t('.content_html') %>
          </div>
      <% else %>
          <div class="card-header card-danger">
            <h2><%= t('.error_header') %></h2>
          </div>
          <div class="card-block">
            <%= t('.error_content_html') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entry/submit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h2><%= t('.header') %></h2>
      </div>
      <div class="card-block">
        <p><%= t('.content_html') %></p>
      </div>
      <div class="card-block">
        <%= form_for @entry do |f| %>
            <div class="col-md-12">
              <div class="form-group row">
                <%= f.label :skater, :class => 'col-md-2 col-form-label' %>
                <div class="input-group col-md-10">
                  <%= f.text_field :skater, :class => 'form-control' %>
                </div>
              </div>

              <div class="form-group row">
                <%= f.label :link, :class => 'col-md-2 col-form-label' %>
                <div class="input-group col-md-10">
                  <div class="input-group-addon"><i class="fa fa-youtube">Youtube</i></div>
                  <div class="input-group-addon">www.youtube.com/watch?v=</div>
                  <%= f.text_field :link, :class => 'form-control' %>
                </div>
              </div>

              <div class="form-group row">
                <%= f.label :mail, :class => 'col-md-2 col-form-label' %>
                <div class="input-group col-md-10">
                  <div class="input-group-addon"><i class="fa fa fa-envelope"></i></div>
                  <%= f.email_field :mail, :class => 'form-control' %>
                </div>
              </div>

              <%= f.fields_for :entry_seasoning do |ff| %>
                  <%= ff.hidden_field :id %>
              <% end %>

              <%= f.submit t(:submit), :class => 'btn btn-primary mt-3 col-md-2 offset-md-10' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/entry/vote.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h2><%= t('.header') %></h2>
      </div>
      <div class="card-block">
        <p><%= t('.content_html', :name => @vote.skate_entry.skater) %></p>
      </div>
      <div class="card-block">
        <%= form_for @vote do |f| %>
            <div class="form-group row">
              <%= f.label :mail, :class => 'col-md-2 col-form-label' %>
              <div class="input-group col-md-10">
                <div class="input-group-addon"><i class="fa fa fa-envelope"></i></div>
                <%= f.email_field :mail, :class => 'form-control' %>
              </div>
            </div>

            <%= f.fields_for :skate_entry do |ff| %>
                <%= ff.hidden_field :id %>
            <% end %>

            <%= f.submit t(:submit), :class => 'btn btn-primary col-md-2 offset-md-10' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-10">
            <h2><%= t(:sponsor_label) %></h2>
          </div>
          <div class="col-md-2">
            <%= link_to(t(:join), sponsor_join_path, :class => "btn btn-success btn-block")  %>
          </div>
        </div>
      </div>
      <div class="card-block">
        <div class="row">
            <% @sponsors.each do |sponsor| %>
              <div class="col-md-3 mb-3">
                <div class="card" id="<%= sponsor.id %>">
                  <%= link_to(sponsor.link, :class => 'card-img-top' ) do  %>
                      <img class='col-md-12' src="<%= sponsor.image %>" />
                  <% end %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12 mt-3">
    <% currentSeason = currentSeasoning %>
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-10">
            <h2><%= t(:season) %> <%= currentSeason.season %> <%= t(:week) %> <%= currentSeason.week %></h2>
          </div>
          <div class="col-md-2">
            <%= link_to(t(:submit), entry_submit_path, :class => "btn btn-success btn-block")  %>
          </div>
        </div>
      </div>
      <div class="card-block">
        <div class="row">
            <% @entries.each do |entry| %>
              <div class="col-md-6 mb-4">
                <div class="card" id="<%= entry.id %>">
                  <div class="card-header">
                    <div class="row">
                      <div class="col-md-6 offset-md-6">
                        <div class="row">
                          <div class="col-md-7">
                            <div class="row">
                              <span class="col-md-7"><%= t(:votes_label) %></span><span class="font-weight-bold h4 col-md-5 text-right"><%= entry.rate %></span>
                            </div>
                          </div>
                          <div class="col-md-5">
                            <%= link_to entry_vote_path(:id => entry.id), :class => "btn btn-primary btn-block" do  %>
                                <i class="fa fa-thumbs-o-up"></i>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-img-top">
                    <div class="embed-responsive embed-responsive-16by9 col-md-12 text-center media-object">
                      <iframe class="embed-responsive-item img-rounded" src="https://www.youtube.com/embed/<%= entry.link %>?autohide=1&showinfo=0" frameborder="0" allowfullscreen></iframe>
                    </div>
                  </div>
                  <div class="card-footer">
                    <h4 class="card-title"><%= entry.skater %></h4>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_banner.erb
<!--
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="col-md-6 offset-md-6">
      <h4>Want to be part of a big project ? Want people to recognize your skateboarding skills ? This is the right place !
        Here you can post your trick each week. We will review the trick and post it if we judge it good enough.
        Then it's your job to share it as much as you can so people can vote for you.
        The video with the most votes at the end of the month will win skate goodies given by our sponsors.</h4>
    </div>
  </div>
</div>
-->

<div id="carouselExampleIndicators" class="carousel slide mb-3" data-ride="carousel" data-interval="6000">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag '/assets/bg_dark.jpg', :class => 'd-block img-fluid', :alt => 'First slide' %>
      <div class="carousel-caption d-none d-md-block">
        <h4><%= t(:entry_about) %></h4>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag '/assets/bg_light.jpg', :class => 'd-block img-fluid', :alt => 'Second slide' %>
      <div class="carousel-caption d-none d-md-block">
        <h4><%= t(:entry_about) %></h4>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span><i class="fa fa-chevron-left fa-3x"></i></span>
    <span class="sr-only"><%= t(:chevron_left) %></span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span><i class="fa fa-chevron-right fa-3x"></i></span>
    <span class="sr-only"><%= t(:chevron_right) %></span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkateSubmit</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-toggleable-md navbar-dark bg-inverse fixed-top">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBarNav" aria-controls="navBarNav" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars fa-inverse"></i>
    </button>
    <div class="collapse navbar-collapse" id="navBarNav">
    <%= link_to(t(:home_label), root_path, class: "navbar-brand") %>
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to(t(:entry_label), entry_index_path, class: "nav-link") %></li>
        <li class="nav-item"><%= link_to(t(:sponsor_label), sponsor_index_path, class: "nav-link") %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render :partial => "layouts/banner", :object => last_entry %>
<div class="container body-content">
  <%= yield %>
  <hr />
  <footer>
    <div class="row">
      <div class="col-md-8"><p>&copy; LeMoose Corporation</p></div>
      <div class="col-md-2"><%= link_to "English", { :locale => 'en' } %></div>
      <div class="col-md-2"><%= link_to "Français", { :locale => 'fr' } %></div>
    </div>
  </footer>
</div>
</body>
</html>

app/views/sponsor/confirm_join.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <% if @sponsor %>
          <div class="card-header card-primary">
            <h1><%= t('.header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.content_html', :name => @sponsor.name) %>
          </div>
      <% else %>
          <div class="card-header card-danger">
            <h1><%= t('.error_header') %></h1>
          </div>
          <div class="card-block">
            <%= t('.error_content_html') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sponsor/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-10">
            <h2><%= t(:sponsor_label) %></h2>
          </div>
          <div class="col-md-2">
            <%= link_to(t(:join), sponsor_join_path, :class => "btn btn-success btn-block")  %>
          </div>
        </div>
      </div>
      <div class="card-block">
        <div class="row">
          <% @sponsors.each do |sponsor| %>
              <div class="col-md-3 mb-3">
                <div class="card" id="<%= sponsor.id %>">
                    <%= link_to(sponsor.link, :class => 'card-img-top' ) do  %>
                      <img class='col-md-12' src="<%= sponsor.image %>" />
                    <% end %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sponsor/join.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h2><%= t('.header') %></h2>
      </div>
      <div class="card-block">
        <%= t('.content_html') %>
      </div>
      <div class="card-block">
        <%= form_for @sponsor do |f| %>
            <div class="form-group row">
              <%= f.label :name, :class => 'col-md-2 col-form-label' %>
              <div class="input-group col-md-10">
                <%= f.text_field :name, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group row">
              <%= f.label :website, :class => 'col-md-2 col-form-label' %>
              <div class="input-group col-md-10">
                <div class="input-group-addon">www</div>
                <%= f.url_field :website, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group row">
              <%= f.label :image, :class => 'col-md-2 col-form-label' %>
              <div class="input-group col-md-10">
                <div class="input-group-addon"><i class="fa fa-photo"></i></div>
                <%= f.url_field :image, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group row">
              <%= f.label :mail, :class => 'col-md-2 col-form-label' %>
              <div class="input-group col-md-10">
                <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                <%= f.email_field :mail, :class => 'form-control' %>
              </div>
            </div>

            <%= f.submit t(:submit), :class => 'btn btn-primary col-md-2 offset-md-10' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sponsor/pending.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-md-12">
          <h2><%= t(:sponsor_label) %></h2>
        </div>
      </div>
    </div>
    <div class="card-block">
      <div class="card-deck-wrapper">
        <div class="card-deck">
          <% @sponsors.each do |sponsor| %>
              <div class="card" id="<%= sponsor.id %>">
                <div class="card-header">
                  <div class="col-md-12">
                    <h4 class="card-title"><%= sponsor.name %></h4>
                  </div>
                </div>
                <div class="card-img-top">
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sponsor/send_join.html.erb
<% if @sponsor %>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h2><%= t('.header') %></h2>
          </div>
          <div class="card-block">
            <%= t('.content_html') %>
          </div>
        </div>
      </div>
    </div>
<% end %>